ingress:
  name: ingress
  exposedServices:
    - intens-fe
    - intens-be
persistentVolumeClaim:
  name: intens-db
services:
  intens-be:
    replicas: 2
    image: intens-praksa-be-server:657768d66c6ec1ba84a2038c2dbeae654bed59d9
    port: 8000
    env:
      DATABASE_URL: "postgresql://intens:intens@intens-db-service:5432/intens"
      FRONTEND_URL: "http://intens-fe-service:3000"
    serviceTargetPort: 8000
    host: intens-be-service
  intens-fe:
    replicas: 1
    image: intens-praksa-fe-server:c4130e152c898264351c4e71da72fcde15a5625f
    port: 3000
    env:
      PORT: "3000"
    serviceTargetPort: 3000
    host: intens.praksa
  intens-db:
    replicas: 1
    image: postgres:16
    imagePullPolicy: Always
    port: 5432
    serviceType: ClusterIP
    env:
      POSTGRES_USER: "intens"
      POSTGRES_PASSWORD: "intens"
      POSTGRES_DB: "intens"
    volumeMounts:
      - name: db-data
        mountPath: /var/lib/postgresql/data
    volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: intens-db-pvc
