ingress:
  name: ingress
persistentVolumeClaim:
  name: intens-db
services:
  intens-be:
    replicas: 2
    image: intens-praksa-be-server:b6e13bbb38cfef3bc6f0c9e13a9e72f2119633ed
    port: 8000
    env:
      DATABASE_URL: "postgresql://intens:intens@intens-db-service:5432/intens"
      FRONTEND_URL: "http://intens-fe-service:3000"
    serviceTargetPort: 8000
    host: intens-be-service
  intens-fe:
    replicas: 1
    image: intens-praksa-fe-server:8f1e565115b91a81ed4374fe2ca02c995c9f34fb
    port: 3000
    env:
      PORT: "3000"
      API_HOST: "intens-be-service"
    serviceTargetPort: 3000
    host: intens.praksa
  intens-db:
    replicas: 1
    image: postgres:16
    imagePullPolicy: Always
    port: 5432
    serviceType: ClusterIP
    env:
      POSTGRES_USER: "intens"
      POSTGRES_PASSWORD: "intens"
      POSTGRES_DB: "intens"
    volumeMounts:
      - name: db-data
        mountPath: /var/lib/postgresql/data
    volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: intens-db-pvc
