{{- $ing := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ing.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  {{- range $name := $ing.exposedServices }}
  {{- $svc := index $.Values.services $name }}
    - host: {{ $svc.host }}-{{ $.Release.Namespace }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}-service
                port:
                  number: {{ $svc.port }}
  {{- end }}