{{- $ing := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ing.name }}
spec:
  ingressClassName: nginx
  rules:
  {{- range $name, $svc := .Values.services }}
    - host: {{ $svc.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}-service
                port:
                  number: {{ $svc.port }}
  {{- end }}